---
title: "Quiz Explore Many Variables"
output: html_document
---

```{r}
#Price Histograms with Facet and Color

# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

# The plot should look something like this.
# http://i.imgur.com/b5xyrOu.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the histogram using
# scale_fill_brewer(type = 'qual')

data(diaomds)
```

```{r}
ggplot(data = diamonds, aes(x = log(price))) +
  geom_histogram(aes(color = cut)) +
  facet_wrap(~color, ncol = 3)
```

```{r}
# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.

# The plot should look something like this.
# http://i.imgur.com/rQF9jQr.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the scatterplot using
# scale_color_brewer(type = 'qual')

ggplot(aes(x = table, y = price), data = diamonds) +
  geom_point(aes(color = cut)) +
  #xlim(50,80)
  scale_x_continuous(breaks = seq(50, 80, 2), 
                     limits = c(50, 80)) +
  scale_color_brewer(type = 'qual')
  theme_minimal()
```

```{r Prices vs. Volume and Diamond Clarity}
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.

# Note: Volume is a very rough approximation of
# a diamond's actual volume.

# The plot should look something like this.
# http://i.imgur.com/excUpea.jpg

# Note: In the link, a color palette of type
# 'div' was used to color the scatterplot using
# scale_color_brewer(type = 'div')

diamonds <- diamonds %>%
  mutate(volume = x * y * z)


ggplot(aes(x = volume, y = price), data = diamonds) +
  geom_point(aes(color = clarity)) +
  scale_y_log10() +
  scale_x_continuous(limits = c(0, quantile(diamonds$volume, 0.99))) +
  scale_color_brewer(type = 'div') 
```

```{r}
# Many interesting variables are derived from two or more others.
# For example, we might wonder how much of a person's network on
# a service like Facebook the user actively initiated. Two users
# with the same degree (or number of friends) might be very
# different if one initiated most of those connections on the
# service, while the other initiated very few. So it could be
# useful to consider this proportion of existing friendships that
# the user initiated. This might be a good predictor of how active
# a user is compared with their peers, or other traits, such as
# personality (i.e., is this person an extrovert?).

# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.

pf <- read.csv('C:/Files/Udacity/Data-Analysis/Notes/Exploratory Data Analysis (R)/R Basics/eda-course-materials/lesson3/pseudo_facebook.tsv', sep = '\t')
#sep="\t" tells R that the file is tab-delimited (use " " for space delimited and "," for comma delimited; use "," for a .csv file)
```

```{r}
pf <- pf %>%
  mutate(prop_initiated = friendships_initiated/friend_count)

#OR
#pf$prop_initiated <- pf$friendships_initiated / pf$friend_count
```

```{r}
summary(pf)
```

```{r}
# Create a line graph of the median proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.

# Recall, we created year_joined.bucket in Lesson 5
# by first creating year_joined from the variable tenure.
# Then, we used the cut function on year_joined to create
# four bins or cohorts of users.

# (2004, 2009]
# (2009, 2011]
# (2011, 2012]
# (2012, 2014]

pf$year_joined <- floor(2014 - pf$tenure/365)
pf$year_joined.bucket <- cut(pf$year_joined, 
                             c(2004, 2009, 2011, 2012, 2014))

ggplot(aes(x = tenure, y = prop_initiated),
       data = subset(pf, !is.na(gender))) +
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)
```

```{r}
# Smooth the last plot you created of
# of prop_initiated vs tenure colored by
# year_joined.bucket. You can bin together ranges
# of tenure or add a smoother to the plot.

# There won't be a solution image for this exercise.
# You will answer some questions about your plot in
# the next two exercises.

ggplot(aes(x = tenure, y = prop_initiated),
       data = subset(pf, !is.na(gender))) +
  #geom_line(stat = 'summary', fun.y = median) +
  geom_smooth(aes(color = year_joined.bucket))
```

```{r}
pf %>%
  filter(year_joined.bucket == "(2012,2014]") %>%
  summarise(avg = mean(prop_initiated, na.rm=TRUE))
```

```{r}
# Create a scatter plot of the price/carat ratio
# of diamonds. The variable x should be
# assigned to cut. The points should be colored
# by diamond color, and the plot should be
# faceted by clarity.

# The plot should look something like this.
# http://i.imgur.com/YzbWkHT.jpg.

# Note: In the link, a color palette of type
# 'div' was used to color the histogram using
# scale_color_brewer(type = 'div')

ggplot(diamonds, aes(x = cut, y = price/carat, color = color)) + 
  geom_jitter() + 
  facet_wrap(~clarity) + 
  scale_color_brewer(type = 'div')
```

```{r}
# The Gapminder website contains over 500 data sets with information about
# the world's population. Your task is to continue the investigation you did at the
# end of Problem Set 4 or you can start fresh and choose a different
# data set from Gapminder.

# If you're feeling adventurous or want to try some data munging see if you can
# find a data set or scrape one from the web.

# In your investigation, examine 3 or more variables and create 2-5 plots that make
# use of the techniques from Lesson 5.

# You can find a link to the Gapminder website in the Instructor Notes.

# Once you've completed your investigation, create a post in the discussions that includes:
#       1. the variable(s) you investigated, your observations, and any summary statistics
#       2. snippets of code that created the plots
#       3. links to the images of your plots

library(ggthemes)
ggplot(pf, aes(x=age, y=friendships_initiated, color=age)) +
        geom_point(alpha = 1 / 5, 
                   position = position_jitter(h=0),
                   aes(size=friendships_initiated / 40)) +
        scale_color_distiller(type = "seq", palette = "YlGnBu") +
        labs(y="Friendships Initiated") +
        scale_x_continuous(limits = c(10,90), breaks = seq(10,90,5)) +
        scale_y_continuous(labels = scales::unit_format("k", 1e-3)) +
        theme_tufte()
```

