---
title: "Lesson 4 Quiz"
output: html_document
---
##Load Diamond Data##
```{r}
library(ggplot2)     #must load the ggplot package first
data(diamonds)       #loads the diamonds data set since it comes with the ggplot package
summary(diamonds)
```

##Price Histogram##
```{r}
# Create a histogram of the price of
# all the diamonds in the diamond data set.
ggplot(aes(x = price), data = diamonds) +
  geom_histogram(binwidth = 100) +
  scale_x_continuous(breaks = seq(0, 18823, 1000))  #long_tailed should be added
```


##Price Histogram Summary##
```{r}
subset(diamonds, price < 500)
```

```{r}
subset(diamonds, price < 250)
```

```{r}
subset(diamonds, price >= 15000, select=c(price))
```

##Cheaper Diamonds##
```{r}
# Explore the largest peak in the
# price histogram you created earlier.

# Try limiting the x-axis, altering the bin width,
# and setting different breaks on the x-axis.

# There won't be a solution video for this
# question so go to the discussions to
# share your thoughts and discover
# what other people find.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Submit your final code when you are ready.
ggplot(aes(x = price), data = diamonds) +
  geom_histogram(binwidth = 25, color = 'black', fill = '#099DD9') +
  scale_x_continuous(breaks = seq(0, 1500, 100), limits = c(0,1500))
ggsave('priceHistogram.png')
```

##Price by Cut Histograms##
```{r}
# Break out the histogram of diamond prices by cut.

# You should have five histograms in separate
# panels on your resulting plot.
ggplot(diamonds) + geom_histogram(aes(x=price), binwidth = 100, 
                                  color = "black", fill = "#099DD9") + 
  ggtitle("Diamonds Price by Cut Histogram") + 
  facet_grid(. ~ cut)
```

##Price by Cut##
```{r}
#Which cut has the highest priced diamond?
#Which cut has the lowest priced diamond?
#Which cut has the lowest median price?
by(diamonds$price,diamonds$cut,summary)
```

##Scales and Multiple Histograms##
```{r}
# In the two last exercises, we looked at
# the distribution for diamonds by cut.

# Run the code below in R Studio to generate
# the histogram as a reminder.
qplot(x = price, data = diamonds) + facet_wrap(~cut)
```

```{r}
# In the last exercise, we looked at the summary statistics
# for diamond price by cut. If we look at the output table, the
# the median and quartiles are reasonably close to each other.

# diamonds$cut: Fair
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     337    2050    3282    4359    5206   18570 
# ------------------------------------------------------------------------ 
# diamonds$cut: Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     327    1145    3050    3929    5028   18790 
# ------------------------------------------------------------------------ 
# diamonds$cut: Very Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     336     912    2648    3982    5373   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Premium
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326    1046    3185    4584    6296   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Ideal
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326     878    1810    3458    4678   18810 

# This means the distributions should be somewhat similar,
# but the histograms we created don't show that.

# The 'Fair' and 'Good' diamonds appear to have 
# different distributions compared to the better
# cut diamonds. They seem somewhat uniform
# on the left with long tails on the right.

# Let's look in to this more.

# Look up the documentation for facet_wrap in R Studio.
# Then, scroll back up and add a parameter to facet_wrap so that
# the y-axis in the histograms is not fixed. You want the y-axis to
# be different for each histogram.

# If you want a hint, check out the Instructor Notes.
ggplot(diamonds) + geom_histogram(aes(x=price), binwidth = 100, 
                                  color = "black", fill = "lightblue") + 
  ggtitle("Diamonds Price by Cut Histogram") + 
  facet_grid(. ~ cut)

ggplot(diamonds) + geom_histogram(aes(x=price)) + 
  ggtitle("Diamonds Price by Cut Histogram") + 
  facet_wrap(~ cut,scales="free_y",ncol = 5)

qplot(x = price, data = diamonds) + facet_wrap(~cut, scales="free")
```

##Price per Carat by Cut##
```{r}
# Create a histogram of price per carat
# and facet it by cut. You can make adjustments
# to the code from the previous exercise to get
# started.

# Adjust the bin width and transform the scale
# of the x-axis using log10.

# Submit your final code when you are ready.
ggplot(diamonds) + geom_histogram(aes(x=price/carat), binwidth = 0.05,
                                  color = "black", fill = "lightblue") +
  ggtitle("Histogram of Price per Carat, facet by Cut.") + 
  scale_x_log10() +
  facet_grid(. ~ cut)
```

##Price Box Plots##
```{r}
# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# For boxplots, we use the "y" parameter for the continuous data and the "x" parameter for the categorical data.
by(diamonds$price, diamonds$color, summary)
ggplot(diamonds) + geom_boxplot(aes(x = color,  y = price, fill = color)) + 
  coord_cartesian(ylim = c(0, 8000)) + 
  scale_y_continuous(breaks = seq(0,8000,500)) +
  ggtitle("Diamonds Price by Color.")
```

##Interquartile range - IQR##
```{r}
#What is the price range for the middle 50% of diamonds with color D?
#What is the price range for the middle 50% of diamonds with color J?
by(diamonds$price, diamonds$color, summary)
```

```{r}
#What is the IQR for diamonds with the best color?
#What is the IQR for diamonds with the worst color?
by(diamonds$price, diamonds$color, IQR)
```

##Price per Carat Box Plots by Color##
```{r}
# Investigate the price per carat of diamonds across
# the different colors of diamonds using boxplots.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.

# SUBMIT YOUR CODE BELOW THIS LINE
# ===================================================================
ggplot(diamonds) + geom_boxplot(aes(x=color,y=price/carat, fill=color)) + 
  scale_y_continuous(breaks = seq(0,8000,500)) + 
  coord_cartesian(ylim = c(0,8000)) + 
  ylab("Price per Carat") +
  ggtitle("Price per Carat by Color")
```

##Carat frequency polygon##
```{r}
#What carat size has a count greater than 2000?
ggplot(diamonds) + geom_freqpoly(aes(x = carat), binwidth = 0.02) + 
  scale_x_continuous(breaks = seq(0,5,0.1)) + 
  ggtitle("Carat Frequency Polygon")
```

##Gapminder data##
```{r}
# The Gapminder website contains over 500 data sets with information about
# the world's population. Your task is to download a data set of your choice
# and create 2-5 plots that make use of the techniques from Lesson 3.

# You might use a simple histogram, a boxplot split over a categorical variable,
# or a frequency polygon. The choice is yours!

# You can find a link to the Gapminder website in the Instructor Notes.

# Once you've completed your investigation, create a post in the discussions that includes:
#       1. any questions you answered, your observations, and summary statistics
#       2. snippets of code that created the plots
#       3. links to the images of your plots

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# ====================================================================================
# I picked the child mortality dataset and first made it 'tidy'
deaths <- read.csv('deaths.csv', header = T, check.names = F)
tidydeaths <- gather(deaths, "year", "death_rate", 2:254, na.rm=TRUE)

# This is the country / region lookup. I made sure that the column for country
# was also 'Country', same as my deaths dataset above
countries <- read.csv('countries.csv', header = T, check.names = F)

# Here's my combined dataset that now includes regions in a column called 'Group'
combined <- left_join(tidydeaths, countries, by = "Country")

# Bonus! :) I converted "year" to "century" with a nice string
combined$century <- paste0(as.character(floor(as.numeric(as.character(combined$year)) / 100)),'00s')
```

##Explory Your Friends' Birthdays##
```{r}
# Your task is to investigate the distribution of your friends'
# birth months and days.

# Here some questions you could answer, and we hope you think of others.

# **********************************************************************

# How many people share your birthday? Do you know them?
# (Reserve time with them or save money to buy them a gift!)

# Which month contains the most number of birthdays?

# How many birthdays are in each month?

# Which day of the year has the most number of birthdays?

# Do you have at least 365 friends that have birthdays on everyday
# of the year?

# **********************************************************************

# You will need to do some data munging and additional research to
# complete this task. This task won't be easy, and you may encounter some
# unexpected challenges along the way. We hope you learn a lot from it though.

# You can expect to spend 30 min or more on this task depending if you
# use the provided data or obtain your personal data. We also encourage you
# to use the lubridate package for working with dates. Read over the documentation
# in RStudio and search for examples online if you need help.

# You'll need to export your Facebooks friends' birthdays to a csv file.
# You may need to create a calendar of your Facebook friends' birthdays
# in a program like Outlook or Gmail and then export the calendar as a
# csv file.

# Once you load the data into R Studio, you can use the strptime() function
# to extract the birth months and birth days. We recommend looking up the
# documentation for the function and finding examples online.

# We've included some links in the Instructor Notes to help get you started.

# Once you've completed your investigation, create a post in the discussions that includes:
#       1. any questions you answered, your observations, and summary statistics
#       2. snippets of code that created the plots
#       3. links to the images of your plots

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation below the line. Submit it when you are ready.
# ===============================================================================

#Load and Cleaning data
library(lubridate)
setwd("C:/Files/Udacity/Data-Analysis/Notes/Exploratory Data Analysis (R)/R Basics/eda-course-materials/lesson3")
birthdays <- read.csv("C:/Files/Udacity/Data-Analysis/Notes/Exploratory Data Analysis (R)/R Basics/eda-course-materials/lesson3/birthdaysExample.csv")

birthdays$dates <- mdy(birthdays$dates)
birthdays$month <- month(birthdays$dates)
birthdays$day <- day(birthdays$dates)
```

```{r}
#Data Processing
summary(birthdays)
table(birthdays$month)
table(birthdays$day)
```

```{r}
#How many people share your birthday? Do you know them?
may.second <- subset(birthdays, month == 05 & day == 02)
nrow(may.second)
```

```{r}
#Which month contains the most number of birthdays?
ggplot(birthdays) + geom_histogram(aes(x = month), color = I('black'), fill = I('#099DD9'),
                                   binwidth = 1) +
  scale_y_discrete() +
  scale_x_discrete(breaks = seq(0,12,1)) + 
  ggtitle("Birthdays per Month")
```

```{r}
#How many birthdays are in each month?
table(birthdays$month)
```

```{r}
#Which day of the year has the most number of birthdays?
ggplot(birthdays) + geom_histogram(aes(x = day),color = I('black'), fill = I('#099DD9'),
                                   binwidth = 1) +
  scale_y_discrete() +
  scale_x_continuous(breaks = seq(0,31,1)) + 
  ggtitle("Birthdays per Day")
```

```{r}
#Do you have at least 365 friends that have birthdays on everyday of the year?
length(unique(birthdays$dates))
```


